// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: api/controller.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControllerService_StreamInput_FullMethodName     = "/api.ControllerService/StreamInput"
	ControllerService_GetFrame_FullMethodName        = "/api.ControllerService/GetFrame"
	ControllerService_ReadMemory_FullMethodName      = "/api.ControllerService/ReadMemory"
	ControllerService_LoadState_FullMethodName       = "/api.ControllerService/LoadState"
	ControllerService_ResetSystem_FullMethodName     = "/api.ControllerService/ResetSystem"
	ControllerService_Pause_FullMethodName           = "/api.ControllerService/Pause"
	ControllerService_Resume_FullMethodName          = "/api.ControllerService/Resume"
	ControllerService_Step_FullMethodName            = "/api.ControllerService/Step"
	ControllerService_GetCPUState_FullMethodName     = "/api.ControllerService/GetCPUState"
	ControllerService_ReadMemoryBlock_FullMethodName = "/api.ControllerService/ReadMemoryBlock"
)

// ControllerServiceClient is the client API for ControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerServiceClient interface {
	// Client streams button states to the emulator
	StreamInput(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputState, Empty], error)
	// RL Endpoints
	// Requests the current frame buffer (pixels) from the PPU
	GetFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FrameResponse, error)
	// Reads a byte from the NES system bus (used to calculate RL rewards/done state)
	ReadMemory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error)
	// Loads an emulator save state from a file, bypassing the title screen
	LoadState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*Empty, error)
	// Triggers a hardware reset of the NES (returns game to title screen)
	ResetSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	// --- VDB (Vibemulator Debugger) Endpoints ---
	Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Step(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetCPUState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CPUStateResponse, error)
	ReadMemoryBlock(ctx context.Context, in *MemoryBlockRequest, opts ...grpc.CallOption) (*MemoryBlockResponse, error)
}

type controllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerServiceClient(cc grpc.ClientConnInterface) ControllerServiceClient {
	return &controllerServiceClient{cc}
}

func (c *controllerServiceClient) StreamInput(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputState, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ControllerService_ServiceDesc.Streams[0], ControllerService_StreamInput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InputState, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerService_StreamInputClient = grpc.BidiStreamingClient[InputState, Empty]

func (c *controllerServiceClient) GetFrame(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReadMemory(ctx context.Context, in *MemoryRequest, opts ...grpc.CallOption) (*MemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryResponse)
	err := c.cc.Invoke(ctx, ControllerService_ReadMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) LoadState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ControllerService_LoadState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ResetSystem(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ControllerService_ResetSystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ControllerService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Resume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ControllerService_Resume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) Step(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ControllerService_Step_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) GetCPUState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CPUStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CPUStateResponse)
	err := c.cc.Invoke(ctx, ControllerService_GetCPUState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerServiceClient) ReadMemoryBlock(ctx context.Context, in *MemoryBlockRequest, opts ...grpc.CallOption) (*MemoryBlockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryBlockResponse)
	err := c.cc.Invoke(ctx, ControllerService_ReadMemoryBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServiceServer is the server API for ControllerService service.
// All implementations must embed UnimplementedControllerServiceServer
// for forward compatibility.
type ControllerServiceServer interface {
	// Client streams button states to the emulator
	StreamInput(grpc.BidiStreamingServer[InputState, Empty]) error
	// RL Endpoints
	// Requests the current frame buffer (pixels) from the PPU
	GetFrame(context.Context, *Empty) (*FrameResponse, error)
	// Reads a byte from the NES system bus (used to calculate RL rewards/done state)
	ReadMemory(context.Context, *MemoryRequest) (*MemoryResponse, error)
	// Loads an emulator save state from a file, bypassing the title screen
	LoadState(context.Context, *StateRequest) (*Empty, error)
	// Triggers a hardware reset of the NES (returns game to title screen)
	ResetSystem(context.Context, *Empty) (*Empty, error)
	// --- VDB (Vibemulator Debugger) Endpoints ---
	Pause(context.Context, *Empty) (*Empty, error)
	Resume(context.Context, *Empty) (*Empty, error)
	Step(context.Context, *Empty) (*Empty, error)
	GetCPUState(context.Context, *Empty) (*CPUStateResponse, error)
	ReadMemoryBlock(context.Context, *MemoryBlockRequest) (*MemoryBlockResponse, error)
	mustEmbedUnimplementedControllerServiceServer()
}

// UnimplementedControllerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServiceServer struct{}

func (UnimplementedControllerServiceServer) StreamInput(grpc.BidiStreamingServer[InputState, Empty]) error {
	return status.Error(codes.Unimplemented, "method StreamInput not implemented")
}
func (UnimplementedControllerServiceServer) GetFrame(context.Context, *Empty) (*FrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFrame not implemented")
}
func (UnimplementedControllerServiceServer) ReadMemory(context.Context, *MemoryRequest) (*MemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemory not implemented")
}
func (UnimplementedControllerServiceServer) LoadState(context.Context, *StateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadState not implemented")
}
func (UnimplementedControllerServiceServer) ResetSystem(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetSystem not implemented")
}
func (UnimplementedControllerServiceServer) Pause(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedControllerServiceServer) Resume(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Resume not implemented")
}
func (UnimplementedControllerServiceServer) Step(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Step not implemented")
}
func (UnimplementedControllerServiceServer) GetCPUState(context.Context, *Empty) (*CPUStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCPUState not implemented")
}
func (UnimplementedControllerServiceServer) ReadMemoryBlock(context.Context, *MemoryBlockRequest) (*MemoryBlockResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadMemoryBlock not implemented")
}
func (UnimplementedControllerServiceServer) mustEmbedUnimplementedControllerServiceServer() {}
func (UnimplementedControllerServiceServer) testEmbeddedByValue()                           {}

// UnsafeControllerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServiceServer will
// result in compilation errors.
type UnsafeControllerServiceServer interface {
	mustEmbedUnimplementedControllerServiceServer()
}

func RegisterControllerServiceServer(s grpc.ServiceRegistrar, srv ControllerServiceServer) {
	// If the following call panics, it indicates UnimplementedControllerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControllerService_ServiceDesc, srv)
}

func _ControllerService_StreamInput_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServiceServer).StreamInput(&grpc.GenericServerStream[InputState, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ControllerService_StreamInputServer = grpc.BidiStreamingServer[InputState, Empty]

func _ControllerService_GetFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetFrame(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReadMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReadMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReadMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReadMemory(ctx, req.(*MemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_LoadState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).LoadState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_LoadState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).LoadState(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ResetSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ResetSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ResetSystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ResetSystem(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Pause(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Resume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Resume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Resume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Resume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_Step_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).Step(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_Step_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).Step(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_GetCPUState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).GetCPUState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_GetCPUState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).GetCPUState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControllerService_ReadMemoryBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryBlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServiceServer).ReadMemoryBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControllerService_ReadMemoryBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServiceServer).ReadMemoryBlock(ctx, req.(*MemoryBlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ControllerService_ServiceDesc is the grpc.ServiceDesc for ControllerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControllerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.ControllerService",
	HandlerType: (*ControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFrame",
			Handler:    _ControllerService_GetFrame_Handler,
		},
		{
			MethodName: "ReadMemory",
			Handler:    _ControllerService_ReadMemory_Handler,
		},
		{
			MethodName: "LoadState",
			Handler:    _ControllerService_LoadState_Handler,
		},
		{
			MethodName: "ResetSystem",
			Handler:    _ControllerService_ResetSystem_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _ControllerService_Pause_Handler,
		},
		{
			MethodName: "Resume",
			Handler:    _ControllerService_Resume_Handler,
		},
		{
			MethodName: "Step",
			Handler:    _ControllerService_Step_Handler,
		},
		{
			MethodName: "GetCPUState",
			Handler:    _ControllerService_GetCPUState_Handler,
		},
		{
			MethodName: "ReadMemoryBlock",
			Handler:    _ControllerService_ReadMemoryBlock_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamInput",
			Handler:       _ControllerService_StreamInput_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/controller.proto",
}
