// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/controller.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_api_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{0}
}

func (x *StateRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type InputState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player 1 or 2
	PlayerIndex int32 `protobuf:"varint,1,opt,name=player_index,json=playerIndex,proto3" json:"player_index,omitempty"`
	// NES Controller Buttons
	A             bool `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	B             bool `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	Select        bool `protobuf:"varint,4,opt,name=select,proto3" json:"select,omitempty"`
	Start         bool `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Up            bool `protobuf:"varint,6,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool `protobuf:"varint,7,opt,name=down,proto3" json:"down,omitempty"`
	Left          bool `protobuf:"varint,8,opt,name=left,proto3" json:"left,omitempty"`
	Right         bool `protobuf:"varint,9,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputState) Reset() {
	*x = InputState{}
	mi := &file_api_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputState) ProtoMessage() {}

func (x *InputState) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputState.ProtoReflect.Descriptor instead.
func (*InputState) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{1}
}

func (x *InputState) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *InputState) GetA() bool {
	if x != nil {
		return x.A
	}
	return false
}

func (x *InputState) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *InputState) GetSelect() bool {
	if x != nil {
		return x.Select
	}
	return false
}

func (x *InputState) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

func (x *InputState) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *InputState) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *InputState) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *InputState) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

type FrameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw pixel data. Can be RGB or RGBA depending on the PPU output.
	Pixels        []byte `protobuf:"bytes,1,opt,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_api_controller_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{2}
}

func (x *FrameResponse) GetPixels() []byte {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type MemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRequest) Reset() {
	*x = MemoryRequest{}
	mi := &file_api_controller_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRequest) ProtoMessage() {}

func (x *MemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRequest.ProtoReflect.Descriptor instead.
func (*MemoryRequest) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{3}
}

func (x *MemoryRequest) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

type MemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          uint32                 `protobuf:"varint,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryResponse) Reset() {
	*x = MemoryResponse{}
	mi := &file_api_controller_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryResponse) ProtoMessage() {}

func (x *MemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryResponse.ProtoReflect.Descriptor instead.
func (*MemoryResponse) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryResponse) GetData() uint32 {
	if x != nil {
		return x.Data
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_controller_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{5}
}

var File_api_controller_proto protoreflect.FileDescriptor

const file_api_controller_proto_rawDesc = "" +
	"\n" +
	"\x14api/controller.proto\x12\x03api\"*\n" +
	"\fStateRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"\xc7\x01\n" +
	"\n" +
	"InputState\x12!\n" +
	"\fplayer_index\x18\x01 \x01(\x05R\vplayerIndex\x12\f\n" +
	"\x01a\x18\x02 \x01(\bR\x01a\x12\f\n" +
	"\x01b\x18\x03 \x01(\bR\x01b\x12\x16\n" +
	"\x06select\x18\x04 \x01(\bR\x06select\x12\x14\n" +
	"\x05start\x18\x05 \x01(\bR\x05start\x12\x0e\n" +
	"\x02up\x18\x06 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\a \x01(\bR\x04down\x12\x12\n" +
	"\x04left\x18\b \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\t \x01(\bR\x05right\"'\n" +
	"\rFrameResponse\x12\x16\n" +
	"\x06pixels\x18\x01 \x01(\fR\x06pixels\")\n" +
	"\rMemoryRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\"$\n" +
	"\x0eMemoryResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\rR\x04data\"\a\n" +
	"\x05Empty2\xda\x01\n" +
	"\x11ControllerService\x120\n" +
	"\vStreamInput\x12\x0f.api.InputState\x1a\n" +
	".api.Empty\"\x00(\x010\x01\x12,\n" +
	"\bGetFrame\x12\n" +
	".api.Empty\x1a\x12.api.FrameResponse\"\x00\x127\n" +
	"\n" +
	"ReadMemory\x12\x12.api.MemoryRequest\x1a\x13.api.MemoryResponse\"\x00\x12,\n" +
	"\tLoadState\x12\x11.api.StateRequest\x1a\n" +
	".api.Empty\"\x00B$Z\"github.com/meadori/vibemulator/apib\x06proto3"

var (
	file_api_controller_proto_rawDescOnce sync.Once
	file_api_controller_proto_rawDescData []byte
)

func file_api_controller_proto_rawDescGZIP() []byte {
	file_api_controller_proto_rawDescOnce.Do(func() {
		file_api_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_controller_proto_rawDesc), len(file_api_controller_proto_rawDesc)))
	})
	return file_api_controller_proto_rawDescData
}

var file_api_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_controller_proto_goTypes = []any{
	(*StateRequest)(nil),   // 0: api.StateRequest
	(*InputState)(nil),     // 1: api.InputState
	(*FrameResponse)(nil),  // 2: api.FrameResponse
	(*MemoryRequest)(nil),  // 3: api.MemoryRequest
	(*MemoryResponse)(nil), // 4: api.MemoryResponse
	(*Empty)(nil),          // 5: api.Empty
}
var file_api_controller_proto_depIdxs = []int32{
	1, // 0: api.ControllerService.StreamInput:input_type -> api.InputState
	5, // 1: api.ControllerService.GetFrame:input_type -> api.Empty
	3, // 2: api.ControllerService.ReadMemory:input_type -> api.MemoryRequest
	0, // 3: api.ControllerService.LoadState:input_type -> api.StateRequest
	5, // 4: api.ControllerService.StreamInput:output_type -> api.Empty
	2, // 5: api.ControllerService.GetFrame:output_type -> api.FrameResponse
	4, // 6: api.ControllerService.ReadMemory:output_type -> api.MemoryResponse
	5, // 7: api.ControllerService.LoadState:output_type -> api.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_controller_proto_init() }
func file_api_controller_proto_init() {
	if File_api_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_controller_proto_rawDesc), len(file_api_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_controller_proto_goTypes,
		DependencyIndexes: file_api_controller_proto_depIdxs,
		MessageInfos:      file_api_controller_proto_msgTypes,
	}.Build()
	File_api_controller_proto = out.File
	file_api_controller_proto_goTypes = nil
	file_api_controller_proto_depIdxs = nil
}
