// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/controller.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Player 1 or 2
	PlayerIndex int32 `protobuf:"varint,1,opt,name=player_index,json=playerIndex,proto3" json:"player_index,omitempty"`
	// NES Controller Buttons
	A             bool `protobuf:"varint,2,opt,name=a,proto3" json:"a,omitempty"`
	B             bool `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	Select        bool `protobuf:"varint,4,opt,name=select,proto3" json:"select,omitempty"`
	Start         bool `protobuf:"varint,5,opt,name=start,proto3" json:"start,omitempty"`
	Up            bool `protobuf:"varint,6,opt,name=up,proto3" json:"up,omitempty"`
	Down          bool `protobuf:"varint,7,opt,name=down,proto3" json:"down,omitempty"`
	Left          bool `protobuf:"varint,8,opt,name=left,proto3" json:"left,omitempty"`
	Right         bool `protobuf:"varint,9,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputState) Reset() {
	*x = InputState{}
	mi := &file_api_controller_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputState) ProtoMessage() {}

func (x *InputState) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputState.ProtoReflect.Descriptor instead.
func (*InputState) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{0}
}

func (x *InputState) GetPlayerIndex() int32 {
	if x != nil {
		return x.PlayerIndex
	}
	return 0
}

func (x *InputState) GetA() bool {
	if x != nil {
		return x.A
	}
	return false
}

func (x *InputState) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *InputState) GetSelect() bool {
	if x != nil {
		return x.Select
	}
	return false
}

func (x *InputState) GetStart() bool {
	if x != nil {
		return x.Start
	}
	return false
}

func (x *InputState) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

func (x *InputState) GetDown() bool {
	if x != nil {
		return x.Down
	}
	return false
}

func (x *InputState) GetLeft() bool {
	if x != nil {
		return x.Left
	}
	return false
}

func (x *InputState) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_controller_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_controller_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_controller_proto_rawDescGZIP(), []int{1}
}

var File_api_controller_proto protoreflect.FileDescriptor

const file_api_controller_proto_rawDesc = "" +
	"\n" +
	"\x14api/controller.proto\x12\x03api\"\xc7\x01\n" +
	"\n" +
	"InputState\x12!\n" +
	"\fplayer_index\x18\x01 \x01(\x05R\vplayerIndex\x12\f\n" +
	"\x01a\x18\x02 \x01(\bR\x01a\x12\f\n" +
	"\x01b\x18\x03 \x01(\bR\x01b\x12\x16\n" +
	"\x06select\x18\x04 \x01(\bR\x06select\x12\x14\n" +
	"\x05start\x18\x05 \x01(\bR\x05start\x12\x0e\n" +
	"\x02up\x18\x06 \x01(\bR\x02up\x12\x12\n" +
	"\x04down\x18\a \x01(\bR\x04down\x12\x12\n" +
	"\x04left\x18\b \x01(\bR\x04left\x12\x14\n" +
	"\x05right\x18\t \x01(\bR\x05right\"\a\n" +
	"\x05Empty2E\n" +
	"\x11ControllerService\x120\n" +
	"\vStreamInput\x12\x0f.api.InputState\x1a\n" +
	".api.Empty\"\x00(\x010\x01B$Z\"github.com/meadori/vibemulator/apib\x06proto3"

var (
	file_api_controller_proto_rawDescOnce sync.Once
	file_api_controller_proto_rawDescData []byte
)

func file_api_controller_proto_rawDescGZIP() []byte {
	file_api_controller_proto_rawDescOnce.Do(func() {
		file_api_controller_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_controller_proto_rawDesc), len(file_api_controller_proto_rawDesc)))
	})
	return file_api_controller_proto_rawDescData
}

var file_api_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_controller_proto_goTypes = []any{
	(*InputState)(nil), // 0: api.InputState
	(*Empty)(nil),      // 1: api.Empty
}
var file_api_controller_proto_depIdxs = []int32{
	0, // 0: api.ControllerService.StreamInput:input_type -> api.InputState
	1, // 1: api.ControllerService.StreamInput:output_type -> api.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_controller_proto_init() }
func file_api_controller_proto_init() {
	if File_api_controller_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_controller_proto_rawDesc), len(file_api_controller_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_controller_proto_goTypes,
		DependencyIndexes: file_api_controller_proto_depIdxs,
		MessageInfos:      file_api_controller_proto_msgTypes,
	}.Build()
	File_api_controller_proto = out.File
	file_api_controller_proto_goTypes = nil
	file_api_controller_proto_depIdxs = nil
}
